// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/checklist/models/checklist_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5318790870837957661),
      name: 'ChecklistItem',
      lastPropertyId: const obx_int.IdUid(7, 3206231188513422429),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6412846179712683893),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3279190470142145244),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6896836776891979758),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6509465600357634271),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6189465586935062073),
            name: 'photoPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6329099478617741934),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3206231188513422429),
            name: 'completedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5318790870837957661),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ChecklistItem: obx_int.EntityDefinition<ChecklistItem>(
        model: _entities[0],
        toOneRelations: (ChecklistItem object) => [],
        toManyRelations: (ChecklistItem object) => {},
        getId: (ChecklistItem object) => object.id,
        setId: (ChecklistItem object, int id) {
          object.id = id;
        },
        objectToFB: (ChecklistItem object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          final photoPathOffset = object.photoPath == null
              ? null
              : fbb.writeString(object.photoPath!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addBool(3, object.isCompleted);
          fbb.addOffset(4, photoPathOffset);
          fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(6, object.completedAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final completedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final photoPathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = ChecklistItem(
              title: titleParam,
              description: descriptionParam,
              isCompleted: isCompletedParam,
              photoPath: photoPathParam,
              createdAt: createdAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..completedAt = completedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(completedAtValue);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChecklistItem] entity fields to define ObjectBox queries.
class ChecklistItem_ {
  /// See [ChecklistItem.id].
  static final id =
      obx.QueryIntegerProperty<ChecklistItem>(_entities[0].properties[0]);

  /// See [ChecklistItem.title].
  static final title =
      obx.QueryStringProperty<ChecklistItem>(_entities[0].properties[1]);

  /// See [ChecklistItem.description].
  static final description =
      obx.QueryStringProperty<ChecklistItem>(_entities[0].properties[2]);

  /// See [ChecklistItem.isCompleted].
  static final isCompleted =
      obx.QueryBooleanProperty<ChecklistItem>(_entities[0].properties[3]);

  /// See [ChecklistItem.photoPath].
  static final photoPath =
      obx.QueryStringProperty<ChecklistItem>(_entities[0].properties[4]);

  /// See [ChecklistItem.createdAt].
  static final createdAt =
      obx.QueryDateProperty<ChecklistItem>(_entities[0].properties[5]);

  /// See [ChecklistItem.completedAt].
  static final completedAt =
      obx.QueryDateProperty<ChecklistItem>(_entities[0].properties[6]);
}
